/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AbbcRouteImport } from './routes/abbc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayInvoiceNumberRouteImport } from './routes/pay/$invoiceNumber'
import { Route as ApiDonationsRegisterRouteImport } from './routes/api/donations/register'
import { Route as ApiCieloCreatePaymentLinkRouteImport } from './routes/api/cielo/create-payment-link'

const AbbcRoute = AbbcRouteImport.update({
  id: '/abbc',
  path: '/abbc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayInvoiceNumberRoute = PayInvoiceNumberRouteImport.update({
  id: '/pay/$invoiceNumber',
  path: '/pay/$invoiceNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsRegisterRoute = ApiDonationsRegisterRouteImport.update({
  id: '/api/donations/register',
  path: '/api/donations/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCieloCreatePaymentLinkRoute =
  ApiCieloCreatePaymentLinkRouteImport.update({
    id: '/api/cielo/create-payment-link',
    path: '/api/cielo/create-payment-link',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbc': typeof AbbcRoute
  '/pay/$invoiceNumber': typeof PayInvoiceNumberRoute
  '/api/cielo/create-payment-link': typeof ApiCieloCreatePaymentLinkRoute
  '/api/donations/register': typeof ApiDonationsRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbc': typeof AbbcRoute
  '/pay/$invoiceNumber': typeof PayInvoiceNumberRoute
  '/api/cielo/create-payment-link': typeof ApiCieloCreatePaymentLinkRoute
  '/api/donations/register': typeof ApiDonationsRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbc': typeof AbbcRoute
  '/pay/$invoiceNumber': typeof PayInvoiceNumberRoute
  '/api/cielo/create-payment-link': typeof ApiCieloCreatePaymentLinkRoute
  '/api/donations/register': typeof ApiDonationsRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbc'
    | '/pay/$invoiceNumber'
    | '/api/cielo/create-payment-link'
    | '/api/donations/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbc'
    | '/pay/$invoiceNumber'
    | '/api/cielo/create-payment-link'
    | '/api/donations/register'
  id:
    | '__root__'
    | '/'
    | '/abbc'
    | '/pay/$invoiceNumber'
    | '/api/cielo/create-payment-link'
    | '/api/donations/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbcRoute: typeof AbbcRoute
  PayInvoiceNumberRoute: typeof PayInvoiceNumberRoute
  ApiCieloCreatePaymentLinkRoute: typeof ApiCieloCreatePaymentLinkRoute
  ApiDonationsRegisterRoute: typeof ApiDonationsRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/abbc': {
      id: '/abbc'
      path: '/abbc'
      fullPath: '/abbc'
      preLoaderRoute: typeof AbbcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$invoiceNumber': {
      id: '/pay/$invoiceNumber'
      path: '/pay/$invoiceNumber'
      fullPath: '/pay/$invoiceNumber'
      preLoaderRoute: typeof PayInvoiceNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/register': {
      id: '/api/donations/register'
      path: '/api/donations/register'
      fullPath: '/api/donations/register'
      preLoaderRoute: typeof ApiDonationsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cielo/create-payment-link': {
      id: '/api/cielo/create-payment-link'
      path: '/api/cielo/create-payment-link'
      fullPath: '/api/cielo/create-payment-link'
      preLoaderRoute: typeof ApiCieloCreatePaymentLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbcRoute: AbbcRoute,
  PayInvoiceNumberRoute: PayInvoiceNumberRoute,
  ApiCieloCreatePaymentLinkRoute: ApiCieloCreatePaymentLinkRoute,
  ApiDonationsRegisterRoute: ApiDonationsRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
